# Generated by Django 5.0 on 2024-01-10 10:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('homeid', models.CharField(blank=True, max_length=50, null=True)),
                ('homelink', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_currency', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_index=True, default='', max_length=10, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=225, null=True)),
                ('estimated_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('beds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('baths', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lot_size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('days_on_market', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('est_annual_tax', models.PositiveIntegerField(blank=True, null=True)),
                ('hoa_fees', models.PositiveIntegerField(blank=True, null=True)),
                ('agent_type', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_email', models.CharField(blank=True, max_length=254, null=True)),
                ('agent_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_agency_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property_Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(default='', max_length=225, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Deed_History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('title_company', models.CharField(blank=True, max_length=50, null=True)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.home')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Home_Images',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.TextField()),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.home')),
            ],
        ),
        migrations.CreateModel(
            name='Mortgage_History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.home')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Price_History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('event', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('change', models.CharField(blank=True, max_length=50, null=True)),
                ('sqft_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.home')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='home',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webApi.property_type'),
        ),
    ]
